<?php

/**
 * @file
 * Citation object view alter for UWS to display Solr metadata.
 */

/**
 * Implements hook_CMODEL_PID_islandora_object_view_alter().
 */
function uwsdora_ir_citationcmodel_islandora_view_object_alter(AbstractObject &$object, &$output) {
  $config_defined = islandora_solr_metadata_display_callback($object);
  if ($config_defined) {
    $description = islandora_solr_metadata_description_callback($object);
    $weight = $output['citation.tab']['metadata']['#weight'];
    if ($description) {
      $output['citation.tab']['description'] = array(
        '#markup' => $description,
        '#weight' => $weight,
      );
    }
    $output['citation.tab']['metadata'] = array(
      '#markup' => $config_defined,
      '#weight' => $weight + 1,
      '#attached' => array(
        'js' => array(
          'misc/form.js',
          'misc/collapse.js',
        ),
      ),
    );
  }
}

/**
 * Implements hook_islandora_required_objects().
 */
function uwsdora_islandora_required_objects(IslandoraTuque $connection) {
  $islandora_path = drupal_get_path('module', 'islandora');
  $module_path = drupal_get_path('module', 'uwsdora');
  $research_collection = $connection->repository->constructObject('uws:researchCollection');
  $research_collection->owner = 'fedoraAdmin';
  $research_collection->label = 'UWS Research Collection';
  $research_collection->models = 'islandora:collectionCModel';
  $research_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // TN Datastream.
  $datastream = $research_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$islandora_path/images/folder.png", FALSE);
  $research_collection->ingestDatastream($datastream);
  // Collection Policy Datastream.
  $datastream = $research_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/research_collection_policy.xml", FALSE);
  $research_collection->ingestDatastream($datastream);

  $thesis_collection = $connection->repository->constructObject('uws:thesisCollection');
  $thesis_collection->owner = 'fedoraAdmin';
  $thesis_collection->label = 'UWS Thesis Collection';
  $thesis_collection->models = 'islandora:collectionCModel';
  $thesis_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // TN Datastream.
  $datastream = $thesis_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$islandora_path/images/folder.png", FALSE);
  $thesis_collection->ingestDatastream($datastream);
  // Collection Policy Datastream.
  $datastream = $thesis_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/thesis_collection_policy.xml", FALSE);
  $thesis_collection->ingestDatastream($datastream);
  return array(
    'uwsdora' => array(
      'title' => 'University of Western Sydney',
      'objects' => array(
        $research_collection,
        $thesis_collection,
      ),
    ),
  );
}

/**
 * Implements hook_process_islandora_solr_metadata_display().
 */
function uwsdora_process_islandora_solr_metadata_display(array &$variables) {
  $emptied_solr_fields = array();
  foreach ($variables['solr_fields'] as $field_name => $values) {
    if (!empty($values['value'])) {
      $emptied_solr_fields[$field_name] = $values;
    }
  }
  $variables['solr_fields'] = $emptied_solr_fields;
}
