<?php

/**
 * @file
 * Citation object view alter for UWS to display Solr metadata.
 */

/**
 * Implements hook_CMODEL_PID_islandora_object_view_alter().
 */
function uwsdora_ir_citationcmodel_islandora_view_object_alter(AbstractObject &$object, &$output) {
  $config_defined = islandora_solr_metadata_display_callback($object);
  if ($config_defined) {
    $description = islandora_solr_metadata_description_callback($object);
    $weight = $output['citation.tab']['metadata']['#weight'];
    if ($description) {
      $output['citation.tab']['description'] = array(
        '#markup' => $description,
        '#weight' => $weight,
      );
    }
    $output['citation.tab']['metadata'] = array(
      '#markup' => $config_defined,
      '#weight' => $weight + 1,
      '#attached' => array(
        'js' => array(
          'misc/form.js',
          'misc/collapse.js',
        ),
      ),
    );
  }

  // Have the google scholar link open in a new tab.
  $markup = $output['citation.tab']['google_scholar_search']['#markup'];
  preg_match_all('~<a(.*?)href="([^"]+)"(.*?)>~', $markup, $matches);
  $link = decode_entities(
    l(
      t('Search for this publication on Google Scholar'),
      $matches[2][0],
      array(
        'attributes' => array(
          'class' => 'scholar-google-scholar-search-link',
          'target' => '_blank',
        ),
      )
    )
  );
  $output['citation.tab']['google_scholar_search']['#markup'] = $link;

  // Adding PDF Download Link.
  $default_viewer = variable_get('islandora_scholar_viewers', array('default' => 'none'));
  if (isset($object['PDF']) && islandora_datastream_access(ISLANDORA_VIEW_OBJECTS, $object['PDF']) &&
    $default_viewer['default'] == 'none' &&
    !isset($output['citation.tab']['pdf_download']['#markup'])
  ) {
    $output['citation.tab']['pdf_download'] = array(
      '#type' => 'item',
      '#markup' => l(
        t('Download PDF'), "islandora/object/$object->id/datastream/PDF/download/citation.pdf",
        array(
          'attributes' => array(
            'class' => 'scholar-pdf-download-link',
          ),
        )
      ),
      '#weight' => $output['citation.tab']['pdf_download']['#weight'],
    );

    if (isset($object['PREVIEW']) && islandora_datastream_access(ISLANDORA_VIEW_OBJECTS, $object['PREVIEW'])) {
      $preview_weight = $output['citation.tab']['preview']['#weight'];
      $output['citation.tab']['preview'] = array(
        '#theme' => 'image',
        '#attributes' => array(
          'alt' => t('PDF Preview'),
        ),
        '#path' => "islandora/object/$object->id/datastream/PREVIEW/view",
        '#weight' => $preview_weight,
      );
    }
  }
}

/**
 * Implements hook_CMODEL_PID_islandora_object_view_alter().
 */
function uwsdora_ir_thesiscmodel_islandora_view_object_alter(AbstractObject &$object, &$output) {
  // Have the google scholar link open in a new tab.
  $markup = $output['citation.tab']['google_scholar_search']['#markup'];
  preg_match_all('~<a(.*?)href="([^"]+)"(.*?)>~', $markup, $matches);
  $link = decode_entities(
    l(
      t('Search for this publication on Google Scholar'),
      $matches[2][0],
      array(
        'attributes' => array(
          'class' => 'scholar-google-scholar-search-link',
          'target' => '_blank',
        ),
      )
    )
  );
  $ouput['citation.tab']['google_scholar_search']['#markup'] = $link;
}

/**
 * Implements hook_islandora_required_objects().
 */
function uwsdora_islandora_required_objects(IslandoraTuque $connection) {
  $islandora_path = drupal_get_path('module', 'islandora');
  $module_path = drupal_get_path('module', 'uwsdora');
  $research_collection = $connection->repository->constructObject('uws:researchCollection');
  $research_collection->owner = 'fedoraAdmin';
  $research_collection->label = 'UWS Research Collection';
  $research_collection->models = 'islandora:collectionCModel';
  $research_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // TN Datastream.
  $datastream = $research_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$islandora_path/images/folder.png", FALSE);
  $research_collection->ingestDatastream($datastream);
  // Collection Policy Datastream.
  $datastream = $research_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/research_collection_policy.xml", FALSE);
  $research_collection->ingestDatastream($datastream);

  $thesis_collection = $connection->repository->constructObject('uws:thesisCollection');
  $thesis_collection->owner = 'fedoraAdmin';
  $thesis_collection->label = 'UWS Thesis Collection';
  $thesis_collection->models = 'islandora:collectionCModel';
  $thesis_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // TN Datastream.
  $datastream = $thesis_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$islandora_path/images/folder.png", FALSE);
  $thesis_collection->ingestDatastream($datastream);
  // Collection Policy Datastream.
  $datastream = $thesis_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/thesis_collection_policy.xml", FALSE);
  $thesis_collection->ingestDatastream($datastream);
  return array(
    'uwsdora' => array(
      'title' => 'University of Western Sydney',
      'objects' => array(
        $research_collection,
        $thesis_collection,
      ),
    ),
  );
}

/**
 * Implements hook_process_islandora_solr_metadata_display().
 */
function uwsdora_process_islandora_solr_metadata_display(array &$variables) {
  $emptied_solr_fields = array();
  foreach ($variables['solr_fields'] as $field_name => $values) {
    if (!empty($values['value'])) {
      $emptied_solr_fields[$field_name] = $values;
    }
  }
  $variables['solr_fields'] = $emptied_solr_fields;
}

/**
 * Implements hook_views_api().
 */
function uwsdora_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'uwsdora') . '/views',
  );
}

/**
 * Implements hook_convert_mods_to_citeproc_jsons_alter().
 */
function uwsdora_convert_mods_to_citeproc_jsons_alter(&$output, $mods) {
  // @see citeproc/includes/converter.inc::convert_mods_to_citeproc_json_page()
  $extract_page_info = function($mods) {
    $pages = $mods->xpath("//mods:mods[1]/mods:relatedItem[@type='host']/mods:part/mods:extent[@unit='pages']");

    if (empty($pages)) {
      $pages = $mods->xpath("//mods:mods[1]/mods:relatedItem[@type='host']/mods:part/mods:extent[@unit='page']");
    }

    $pages = (!empty($pages) ? $pages[0] : NULL);
    if ($pages) {
      add_mods_namespace($pages);

      $total = $pages->xpath('mods:total');
      $total = (!empty($total) ? (string) $total[0] : NULL);

      $list = $pages->xpath('mods:list');
      $list = (!empty($list) ? (string) $list[0] : NULL);

      $start = $pages->xpath('mods:start');
      $start = (!empty($start) ? (string) $start[0] : NULL);

      $end = $pages->xpath('mods:end');
      $end = (!empty($end) ? (string) $end[0] : NULL);

      if ($total) {
        $output = $total;
      }
      elseif ($list) {
        $output = $list;
      }
      elseif ($start) {
        $output = $start;

        if ($end) {
          $output .= "-" . $end;
        }
      }
      return $output;
    }
  };

  $output['page'] = $extract_page_info($mods);
  $output['volume'] = (int) convert_mods_to_citeproc_json_query($mods, '//mods:mods[1]/mods:relatedItem[@type="host"]/mods:part/mods:detail[@type="volume"]/mods:number');
  $output['issue'] = (int) convert_mods_to_citeproc_json_query($mods, '//mods:mods[1]/mods:relatedItem[@type="host"]/mods:part/mods:detail[@type="issue"]/mods:number');
}

/**
 * Implements hook_islandora_view_object_alter().
 */
function uwsdora_islandora_view_object_alter(&$object, &$rendered) {

  if (isset($object['MODS'])) {
    $document = new DOMDocument();
    $document->loadXML($object['MODS']->content);

    if ($document) {
      $xpath = new DOMXpath($document);
      $xpath->registerNamespace('mods', 'http://www.loc.gov/mods/v3');

      $title = $xpath->evaluate('normalize-space(/mods:mods/mods:titleInfo[not(@type)]/mods:title)');
      $title_alternative = $xpath->evaluate('normalize-space(/mods:mods/mods:titleInfo[@type="alternative"]/mods:title)');

      if (!empty($title) && !empty($title_alternative)) {
        drupal_set_title(t("<span class='uwsdora-mods-title'>@title1</span><br/><span class='uwsdora-mods-title-alternative'>@title2</span>", array('@title1' => $title, '@title2' => $title_alternative)), PASS_THROUGH);
      }
    }
  }
}
